[project]
name = "sentence-miner"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flask>=3.1.0",
    "genanki>=0.13.1",
    "gunicorn>=23.0.0",
]
